app:
  generator:
    pdgf:
      home:
        url: file:/home/mateusz/Documents/Praca Magisterska/PDGF/PDGFEnvironment
      datageneration:
        seed: 87467532L
        rng: PdgfDefaultRandom
        scalefactor: 10
        size: 10
        identifier-field-name: __identifier__
        tables:
          baseSize: 10
        properties:
          __long__test__:
            distribution:
              type: Beta
              beta: 2.0
              alpha: 1.9977
          birthDate:
            constraints:
              maxLength: 1940-01-01T00:00:00Z
              minLength: 1942-01-01T00:00:00Z
            precision: YEARS
        dictionaries:
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/xsd_language_dict.txt
            supportedDatatypes:
              - RDFS_LITERAL
              - XSD_LANGUAGE
              - RDF_LANG_STRING
            keywords:
              conceptKeywords:
                - language tag
                - lang
              propertyKeywords:
                - prop1
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/first_names_female.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              conceptKeywords:
                - female person
                - female
                - woman
              propertyKeywords:
                - first name
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/first_names_male.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              conceptKeywords:
                - male person
                - male
                - man
              propertyKeywords:
                - first name
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/first_names.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              conceptKeywords:
                - person
              propertyKeywords:
                - first name
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/last_names.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              conceptKeywords:
                - person
              propertyKeywords:
                - last name
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/mail_provider.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              propertyKeywords:
                - email provider
          - url: file:/home/mateusz/IdeaProjects/ontology-data-generator/datastore/dictionary/personal_data/gender.dict
            supportedDatatypes:
              - XSD_STRING
            keywords:
              conceptKeywords:
                - person
              propertyKeywords:
                - gender
            constraints:
              maxLength: 6
              minLength: 4